namespace CodingTracker.TerrenceLGee.TrackerUi.Helpers;

public static class ConsoleHelpers
{
    private static readonly string[] ConsoleColors =
    [
        "teal",
        "silver",
        "lime",
        "yellow",
        "fuchsia",
        "aqua",
        "springgreen3",
        "darkcyan",
        "lightseagreen",
        "deepskyblue2",
        "green3_1",
        "cyan3",
        "darkturquoise",
        "turquoise2",
        "mediumspringgreen",
        "cyan2",
        "cyan1",
        "royalblue1",
        "darkseagreen4",
        "steelblue",
        "chartreuse3",
        "cadetblue",
        "cadetblue_1",
        "skyblue3",
        "steelblue1",
        "palegreen3",
        "seagreen3",
        "aquamarine3",
        "mediumturquoise",
        "steelblue1_1",
        "seagreen1_1",
        "aquamarine1",
        "darkslategray2",
        "mediumpurple",
        "lightslateblue",
        "darkolivegreen3",
        "darkseagreen",
        "lightskyblue3",
        "lightskyblue3_1",
        "skyblue2",
        "palegreen1",
        "aquamarine1_1",
        "darkslategray1",
        "lightsalmon3",
        "rosybrown",
        "grey63",
        "darkkhaki",
        "navajowhite3",
        "lightsteelblue",
        "lightcyan3",
        "lightskyblue1",
        "palegreen1_1",
        "darkseagreen1",
        "lightgoldenrod3",
        "mistyrose3",
        "khaki3",
        "lightgoldenrod2",
        "darkolivegreen1",
        "honeydew2",
        "lightgoldenrod2_1",
        "navajowhite1",
        "mistyrose1",
        "cornsilk1",
    ];

    public static string GetRandomColor()
    {
        return ConsoleColors[Random.Shared.Next(ConsoleColors.Length - 1)];
    }
}